INSERT OR IGNORE INTO `jobs` (`id`,`company`,`title`,`role_family`,`role_type`,`recruitment_track`,`location`,`experience_level`,`summary`,`skills_json`,`ai_skills_json`,`bonus_signals_json`,`evidence_json`,`source_tier`,`source_url`,`source_job_id`,`source_published_at`,`content_hash`,`cluster_key`,`status`) VALUES
('DeepSeek-e8f2004c-6599-42cd-b587-176ffc3ff1a3','DeepSeek','AI 产品经理','AI产品/运营','产品岗','实习 / 社会招聘','北京海淀 / 杭州拱墅','实习或全职；Harness 方向通常 2 年以上，优秀者可放宽','把前沿模型能力转化为真实产品，并分别负责 AI 产品与 Agent Harness 的路线、指标、用户反馈和模型协同。','["产品规划","用户洞察","数据分析","项目管理","UI/UX"]','["Agent","KV Cache","Tool Use","Reasoning","Planning","Skills","MCP","Memory","Subagent","Multi-Agent"]','["Agent / AI Coding / Workflow 深度使用","能使用 vibe coding 写代码","工程背景或代码能力"]','["招聘方向 【实习/全职】 ： AI 产品方向、Agent Harness 产品方向","是 AI 产品深度用户，对模型能力边界、不同产品的体验差异和用户场景有真实体感","能够使用 vibe coding 写代码，不一定需要技术背景","理解 LLM API、KV Cache、Agent Loop、Tool Use、Reasoning、Planning、Skills、MCP、Memory、Subagent、Multi-Agent 等相关概念","深度使用过 Claude Code、Cowork、Codex、Cursor、OpenCode、GitHub Copilot、Manus、OpenClaw、Hermes 等类似产品"]','S｜DeepSeek 官方招聘','https://talent.deepseek.com/job/e8f2004c-6599-42cd-b587-176ffc3ff1a3','e8f2004c-6599-42cd-b587-176ffc3ff1a3',NULL,'deepseek-ai-pm-20260821','AI产品/运营','在招'),
('DeepSeek-bdffaaf8-5d88-4aa5-9869-8ab76fcd862a','DeepSeek','通用 Agent 数据产品经理（办公/生活/搜索）','AI产品/运营','产品岗','实习 / 社会招聘','北京海淀 / 杭州拱墅','未明示','围绕 AI 搜索与自主任务执行，推进 Agent 能力、自动化评测归因和高质量数据生产管线。','["评测体系","归因分析","数据生产","指标体系"]','["Agent","AI搜索","Prompt Engineering","Vibe Coding","模型评测"]','["Agent 产品深度使用或构建","自动化工作流设计","大模型数据构造经验"]','["定义并推进大模型在真实任务场景中的 Agent 能力","设计并落地多维度自动化评测与归因体系","设计并迭代高质量、高多样性的数据生产管线","理解模型训练与优化的基本原理，熟悉模型评测方法，精通 prompt engineering 和（vibe）coding"]','S｜DeepSeek 官方招聘','https://talent.deepseek.com/job/bdffaaf8-5d88-4aa5-9869-8ab76fcd862a','bdffaaf8-5d88-4aa5-9869-8ab76fcd862a',NULL,'deepseek-agent-data-pm-20260821','AI产品/运营','在招'),
('DeepSeek-141a78cd-784f-4139-9b72-8046afeec4e4','DeepSeek','专业领域数据产品经理（小语种、医学法律等学科）','AI产品/运营','产品岗','实习 / 社会招聘','北京海淀 / 杭州拱墅','本科生 / 硕士 / 博士均可，重专业纵深','将专业判断转化为模型评测维度、自动化评估方式和数据规范，定位模型短板并设计优化路径。','["专业判断","评测体系","数据规范","用户需求"]','["大模型","模型训练","Prompt Engineering","Vibe Coding"]','["专业知识纵深","可快速验证想法"]','["构建模型评测体系","建设高质量数据","能够敏锐感知不同模型的能力边界与差异","能将专业知识与审美判断转化为可度量的评测维度与数据规范"]','S｜DeepSeek 官方招聘','https://talent.deepseek.com/job/141a78cd-784f-4139-9b72-8046afeec4e4','141a78cd-784f-4139-9b72-8046afeec4e4',NULL,'deepseek-domain-data-pm-20260821','AI产品/运营','在招'),
('DeepSeek-0238c1b1-7f2d-4b53-84da-581127a62954','DeepSeek','AI 创作数据产品经理','AI产品/运营','产品岗','实习 / 社会招聘','北京海淀 / 杭州拱墅','未明示','围绕文学与功能写作定义理想输出、数据质量标准和评测体系，推动模型创作能力优化。','["文本审美","评测体系","数据规范","质量校验"]','["大模型写作","模型训练","AI创作"]','["文学或实用文本长期实践","能借助工具支撑数据生产"]','["制定数据质量标准与评估体系","了解不同模型的风格倾向与能力边界","能将审美判断转化为可度量的评测维度与数据规范","具备一定动手能力，能借助工具高效支撑数据生产与质量校验"]','S｜DeepSeek 官方招聘','https://talent.deepseek.com/job/0238c1b1-7f2d-4b53-84da-581127a62954','0238c1b1-7f2d-4b53-84da-581127a62954',NULL,'deepseek-creative-data-pm-20260821','AI产品/运营','在招'),
('DeepSeek-b8e62d9e-5cfb-4f24-bb6b-549bf45e1ee0','DeepSeek','情感智能数据产品经理','AI产品/运营','产品岗','实习 / 社会招聘','北京海淀 / 杭州拱墅','未明示','负责角色扮演与情感陪伴场景的模型能力优化，从 Badcase 归因、数据生产和系统性评测推动体验提升。','["Badcase归因","用户洞察","同理心","系统性评测"]','["大模型","Vibe Coding","模型训练","模型优化数据"]','["模型优化数据生产经验","系统性评测经验"]','["负责 DeepSeek 模型在角色扮演与情感陪伴场景下的能力优化","深入挖掘角色扮演与情感陪伴场景中的 Badcase","深度使用过前沿主流大模型，熟悉其交互特点与能力边界","能通过 Vibe Coding 快速验证想法"]','S｜DeepSeek 官方招聘','https://talent.deepseek.com/job/b8e62d9e-5cfb-4f24-bb6b-549bf45e1ee0','b8e62d9e-5cfb-4f24-bb6b-549bf45e1ee0',NULL,'deepseek-emotion-data-pm-20260821','AI产品/运营','在招'),
('Kimi-campus-product-manager','Kimi（月之暗面）','产品经理','AI产品/运营','产品岗','校园招聘 / 实习','以官方投递页为准','在校生 / 应届生','月之暗面官方校园招聘公开的产品经理方向；当前品牌页未公开完整职责，因此不扩写技术栈。','["产品规划"]','["AGI"]','[]','["月之暗面 Moonshot AI 校园招聘页，汇总 Kimi 实习与校招岗位，欢迎有志于 AGI 的人才加入。","查看产品经理详情"]','S｜Kimi 官方校园招聘','https://careers.kimi.com/campus','campus-product-manager',NULL,'kimi-campus-pm-20260821','AI产品/运营','在招'),
('Kimi-campus-user-operations','Kimi（月之暗面）','用户运营','AI产品/运营','运营岗','校园招聘 / 实习','以官方投递页为准','在校生 / 应届生','月之暗面官方校园招聘公开的用户运营方向；当前品牌页未公开完整职责，因此不扩写技术栈。','["用户运营"]','["AGI"]','[]','["月之暗面 Moonshot AI 校园招聘页，汇总 Kimi 实习与校招岗位，欢迎有志于 AGI 的人才加入。","查看用户运营详情"]','S｜Kimi 官方校园招聘','https://careers.kimi.com/campus','campus-user-operations',NULL,'kimi-campus-ops-20260821','AI产品/运营','在招'),
('智谱AI-social-product-project','智谱AI','产品经理/项目经理（社招）','通用产品','产品岗','社会招聘','深圳 / 上海 / 杭州 / 成都 / 北京 / 吉隆坡','未明示','负责项目计划、风险管理与质量管理等工作；官网未公开更细技术栈，因此不做推断。','["项目管理","风险管理","质量管理"]','[]','[]','["产品经理/项目经理（社招）","项目计划、风险管理、质量管理等"]','S｜智谱AI 官方招聘','https://www.zhipuai.cn/zh/joinus','social-product-project',NULL,'zhipu-social-product-20260821','通用产品','在招'),
('智谱AI-campus-operations','智谱AI','运营（校招）','AI产品/运营','运营岗','校园招聘','深圳 / 上海 / 杭州 / 成都 / 北京 / 吉隆坡','应届生','结合大模型技术优势，参与设计创新的 AI 解决方案。','["业务抽象","解决方案设计"]','["大模型","AI解决方案"]','[]','["运营（校招）","结合大模型技术优势，参与设计创新的AI解决方案"]','S｜智谱AI 官方招聘','https://www.zhipuai.cn/zh/joinus','campus-operations',NULL,'zhipu-campus-ops-20260821','AI产品/运营','在招');
